#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  2 18:09:12 2026

@author: thomas
"""
import matplotlib.pyplot as plt
import numpy as np
def peak_finder(freqs, data):
    omega = 0
    for i in range(0,100):
        omega += 2*freqs[np.argmax(data*(np.random.normal(0,1,len(data))**2))]
        
    return omega/100
res = 100
colour_matrix = np.zeros((res,res))
for q in range(0,res):
    gam = 2*(q + 1)/res
    if gam > 1:
        break
    else:
        for p in range(0,res):
            a = np.zeros(1000)
            b = np.zeros(1000)
            c = np.zeros(1000)
            lam =  2*(p + 1)/res
            colour_matrix[int(res - p - 1)][int(q)] = 0.5*(lam*(1-gam))**0.5
            freqs = np.linspace(0, 1,1000)
            blank = np.ones(len(freqs))
            fft = (freqs*freqs + blank*(lam + gam)**2)/((lam*(1-gam)*blank - freqs*freqs)**2 + freqs*freqs*(lam*(1+lam)/(lam+gam))**2)
            colour_matrix[int(res - p - 1)][int(q)] = peak_finder(freqs,fft)#(a[np.argmax(b)]+0.5*(lam*(1-gam))**0.5)

im = plt.imshow(colour_matrix, cmap='viridis')
fig, ax = plt.subplots()

ax.imshow(colour_matrix, extent=[0, 2, 0, 2])

im = ax.imshow(colour_matrix, extent=[0, 2, 0, 2])
ax.set_xlabel("$\gamma$")
ax.set_ylabel("$\lambda$")

fig.colorbar(im, label = "peak frequency")
ax.set_box_aspect(1)

plt.show()
